### Numpy 

In [4]:
import numpy as np
np.__version__

'2.1.3'

In [3]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 11:23:37) [Clang 14.0.6 ]'

### Creating List 

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

### Covert List to Array

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(5,0)
arr


array([0, 1, 2, 3, 4, 5])

In [12]:
type(my_list)

list

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(20,10)

array([], dtype=int64)

In [19]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [20]:
np.zeros(3)   # Parameter

array([0., 0., 0.])

In [21]:
np.zeros(3, dtype=int). # hyperparameter

array([0, 0, 0])

In [23]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [25]:
np.zeros([3,2],dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [26]:
np.ones(2)

array([1., 1.])

In [27]:
np.ones([3,2,2],dtype=int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [29]:
np.ones([20,10],dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
rand(3,2)

NameError: name 'rand' is not defined

In [33]:
np.random.rand(1,2)

array([[0.06163629, 0.68632344]])

In [37]:
np.random.randint(2)

1

In [43]:
np.random.randint(4,8)

5

In [45]:
np.random.randint(1,8,100)

array([1, 3, 2, 7, 5, 4, 3, 5, 6, 3, 3, 2, 2, 6, 4, 7, 4, 4, 2, 7, 2, 6,
       5, 1, 5, 3, 7, 1, 2, 1, 2, 7, 1, 7, 1, 4, 6, 3, 7, 1, 7, 2, 6, 3,
       5, 3, 5, 3, 1, 1, 3, 7, 4, 5, 7, 6, 3, 4, 7, 3, 6, 5, 3, 6, 5, 7,
       6, 4, 3, 1, 1, 4, 5, 1, 1, 4, 7, 7, 5, 3, 3, 3, 5, 3, 4, 2, 7, 1,
       5, 3, 4, 4, 4, 4, 7, 7, 4, 2, 3, 6])

In [46]:
np.random.randint(10,40,(10,10))

array([[17, 18, 14, 32, 35, 34, 32, 19, 22, 23],
       [10, 21, 22, 31, 32, 39, 28, 25, 10, 39],
       [20, 17, 31, 15, 13, 22, 12, 30, 21, 39],
       [35, 21, 22, 21, 30, 13, 16, 21, 29, 20],
       [19, 15, 21, 33, 24, 11, 19, 29, 17, 24],
       [21, 20, 19, 37, 18, 20, 39, 31, 34, 28],
       [23, 31, 15, 19, 20, 31, 10, 35, 24, 16],
       [14, 27, 11, 21, 38, 30, 20, 34, 31, 25],
       [22, 32, 36, 12, 36, 15, 25, 35, 25, 21],
       [35, 17, 13, 37, 19, 34, 12, 36, 20, 36]])

In [49]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Slicing in Matrix

In [50]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 18, 18, 11],
       [18, 15, 11, 10],
       [11, 16, 18, 13],
       [14, 11, 14, 14],
       [11, 12, 12, 19]])

In [51]:
b[:]

array([[17, 18, 18, 11],
       [18, 15, 11, 10],
       [11, 16, 18, 13],
       [14, 11, 14, 14],
       [11, 12, 12, 19]])

In [52]:
b[1:2]

array([[18, 15, 11, 10]])

In [53]:
b[0]

array([17, 18, 18, 11])

In [54]:
b[0:5]

array([[17, 18, 18, 11],
       [18, 15, 11, 10],
       [11, 16, 18, 13],
       [14, 11, 14, 14],
       [11, 12, 12, 19]])

In [56]:
b[0,1]

np.int64(18)

In [57]:
b[::-1]

array([[11, 12, 12, 19],
       [14, 11, 14, 14],
       [11, 16, 18, 13],
       [18, 15, 11, 10],
       [17, 18, 18, 11]])

In [58]:
b[::-2]

array([[11, 12, 12, 19],
       [11, 16, 18, 13],
       [17, 18, 18, 11]])

In [59]:
b[-3,-3]

np.int64(16)

In [60]:
arr

array([0, 1, 2, 3, 4, 5])

In [61]:
arr.max()

np.int64(5)

In [62]:
arr.min()

np.int64(0)

In [63]:
b[3:]

array([[14, 11, 14, 14],
       [11, 12, 12, 19]])

In [64]:
b

array([[17, 18, 18, 11],
       [18, 15, 11, 10],
       [11, 16, 18, 13],
       [14, 11, 14, 14],
       [11, 12, 12, 19]])

In [65]:
b[0]

array([17, 18, 18, 11])

In [66]:
b[:1]

array([[17, 18, 18, 11]])

In [67]:
b[0:5,0:6]

array([[17, 18, 18, 11],
       [18, 15, 11, 10],
       [11, 16, 18, 13],
       [14, 11, 14, 14],
       [11, 12, 12, 19]])